extends SceneTree
const Materials = preload("res://view/miniature_materials.gd")
func _initialize() -> void:
	var ground = Materials.ground_material()
	assert(ground.albedo_texture != null and ground.normal_texture != null)
	assert(ground.uv1_world_triplanar)
	assert(ground.albedo_texture.get_image().has_mipmaps())
	assert(ground.normal_texture.get_image().has_mipmaps())
	assert(ground.vertex_color_use_as_albedo and not ground.vertex_color_is_srgb)
	for mat in [Materials.stone_material(),Materials.wood_material(),Materials.token_stone_material(Color("e7ddc4")),Materials.metal_material(Color("9d8658"))]:
		assert(mat.normal_enabled and mat.roughness_texture != null)
		assert(mat.texture_filter == BaseMaterial3D.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS)
	var ui = Materials.frame_style(Color("e9e1ce"))
	assert(ui.texture != null)
	assert(ui.get_texture_margin(SIDE_TOP) == 12.0)
	assert(ui.texture.get_image().get_pixel(0,0).a < 0.01)
	var felt = Materials.metal_material(Color("293f3c"),0.0,0.94)
	assert(is_equal_approx(felt.roughness,0.94))
	assert(felt.roughness_texture == null)
	assert(Materials.frame_style(Color("303e40"),Color("687165"),8.0,"button").get_texture_margin(SIDE_TOP) == 4.0)
	assert(Materials.frame_style(Color("fbfaf3"),Color("687165"),8.0,"field").get_texture_margin(SIDE_TOP) == 3.0)
	assert(Materials.range_material().shader != null)
	print("PASS: textured miniature materials and StyleBoxTexture API, correct linear vertex-color handoff")
	quit(0)
