extends SceneTree
## Actual main scene wiring with authored offline input, not live model quality.
const Main = preload("res://main.tscn")
const Adapter = preload("res://view/ai_gm_playtest/adapter.gd")
const Story = preload("res://tests/experimental/ai_gm_rebuilt/story_fixture.gd")
var scene
var count := 0
var failed: Array[String] = []
func check(value: bool, description: String) -> void:
	count += 1
	if not value: failed.append(description); printerr("FAIL: " + description)
func _initialize() -> void: call_deferred("run_tests")
func run_tests() -> void:
	scene = Main.instantiate(); root.add_child(scene)
	await process_frame
	var old_state: Dictionary = scene.game.state.duplicate(true)
	check(not scene.playtest_mode and scene.board.tiles.size() == 61, "starts with original v9")
	scene.switch_playtest(true)
	check(scene.playtest_mode and scene.playtest_panel.visible and scene.board.tiles.size() == 19, "menu enters rendered 19-cell new mode")
	check(scene.game.state == old_state, "v9 exact world preserved")
	scene.start_demo()
	check(scene.active_action.is_empty() and scene.goal.text.is_empty() and scene.tools_menu.get_popup().is_item_disabled(scene.tools_menu.get_popup().get_item_index(5)), "recorded AI replay is disabled in authored test mode")
	check(scene.map_stats_label.text.contains("演示") and scene.relay_note.text.contains("非正式"), "demo rule visibly labelled")
	var before: Dictionary = scene.playtest.engine.save_data()
	scene.on_hex_selected(Vector2i(1, 0))
	check(scene.selected == Vector2i(1, 0) and scene.active_action.is_empty() and scene.playtest.engine.save_data() == before, "tile click only focuses")
	scene.goal.text = ""; scene.submit_action()
	check(scene.active_action.is_empty() and scene.playtest.engine.save_data() == before, "empty UI text cannot execute focus")
	scene.playtest_fixture()
	check(scene.goal.text == Adapter.FIXTURE_GOAL and scene.active_action.is_empty(), "fixture first click fills text only")
	scene.submit_action()
	check(scene.playtest.phase() == "awaiting_assessment" and not scene.active_action.is_empty(), "submit always requires assessment")
	check(not scene.goal.editable and scene.cancel_button.visible and not scene.cancel_button.disabled, "awaiting controls preserve cancellable explicit text")
	check(scene.current_request.context.attention_focus.id == "hex_1_0", "focus frozen as context not text target")
	scene.switch_playtest(false)
	check(scene.playtest_mode and scene.playtest.phase() == "awaiting_assessment", "mode switch cannot drop unfinished intent")
	scene.import_text.text = "{bad JSON"; scene.import_decision()
	check(scene.playtest.phase() == "awaiting_assessment" and scene.playtest.state_copy().state_version == 0, "invalid JSON preserves current phase/facts")
	scene.save_game(); scene.load_game()
	check(scene.playtest.phase() == "awaiting_assessment" and scene.goal.text == Adapter.FIXTURE_GOAL, "awaiting save UI resumes exact intent")
	scene.playtest_fixture()
	check(scene.playtest.phase() == "ready_roll" and scene.roll_button.visible and not scene.roll_button.disabled, "valid authored assessment exposes once-only execution")
	check(scene.playtest_panel.authority.text.contains("≤5000") and scene.playtest_panel.authority.text.contains("≤8000"), "authoritative thresholds displayed")
	scene.save_game(); scene.load_game()
	check(scene.playtest.phase() == "ready_roll" and scene.roll_button.text.contains("结算一次"), "prepared reload UI stays one-time execution")
	scene.roll_dice()
	var rolls: Array = scene.playtest.action_copy().rolls.duplicate(true)
	check(scene.playtest.phase() == "rolled" and scene.roll_button.text.contains("暂存"), "UI execution locks actual rolls then offers staging")
	check(scene.cancel_button.disabled and not scene.goal.editable, "rolled cannot cancel or edit intent")
	check(scene.playtest_panel.authority.text.contains("实掷"), "real public dice displayed")
	scene.cancel_pending()
	check(scene.playtest.phase() == "rolled" and scene.playtest.action_copy().rolls == rolls, "UI cancellation attempt cannot reroll")
	scene.save_game(); scene.load_game()
	check(scene.playtest.phase() == "rolled" and scene.playtest.action_copy().rolls == rolls and scene.roll_button.text.contains("暂存"), "rolled UI resumes without reroll")
	before = scene.playtest.state_copy()
	scene.roll_dice()
	check(scene.playtest.phase() == "staged" and scene.playtest.state_copy() == before, "UI staging does not publish facts")
	check(scene.playtest_panel.authority.text.contains("未提交") and scene.current_request.phase == "narration", "staged authority visibly provisional and optional narration exported")
	var request: Dictionary = scene.current_request
	var narrative := {"schema_version": "ai_gm_narration/v1", "action_id": request.action_id, "state_version": request.state_version, "context_hash": request.context_hash, "narration": "叙事声称城门开启；事实仍以权威栏为准。"}
	check(scene.apply_decision(narrative) and scene.journal.get_parsed_text().contains("语义未验证"), "prose labelled uncertified independent display")
	narrative["patches"] = []
	check(not scene.apply_decision(narrative) and scene.playtest.phase() == "staged" and scene.playtest.state_copy() == before, "invalid narrative cannot unstage/alter numbers")
	scene.save_game(); scene.load_game()
	check(scene.playtest.phase() == "staged" and scene.roll_button.text.contains("提交"), "staged UI reload preserves matching commit")
	scene.roll_dice()
	check(scene.playtest.phase() == "idle" and scene.playtest.state_copy().state_version == 1, "numeric commit works despite narrative failure")
	check(scene.playtest.state_copy().items.item_wine.quantity == 2 and scene.playtest.state_copy().actors.actor_player.stamina.current == 7, "UI authority costs applied exactly once")
	check(scene.active_action.is_empty() and scene.goal.editable and scene.submit_button.visible, "committed UI permits new action")
	check(scene.playtest_panel.authority.text.contains("已提交") and scene.current_request.phase == "narration", "persistent committed numbers alongside optional narration")
	before = scene.playtest.state_copy(); scene.roll_dice()
	check(scene.playtest.state_copy() == before, "repeated UI advance cannot double commit")
	scene.save_game(); scene.load_game()
	check(scene.playtest.phase() == "idle" and scene.playtest.state_copy() == before and scene.playtest.authoritative_result().rolls == rolls, "committed UI load restores authority/history")
	scene.switch_playtest(false)
	check(not scene.playtest_mode and scene.board.tiles.size() == 61 and scene.game.state == old_state, "return to original 61-cell v9 exact world")
	check(not scene.playtest_panel.visible and scene.import_dialog.title.contains("模型裁定"), "v9 controls/protocol restored")
	scene.goal.text = "观察河岸"; scene.submit_action()
	check(scene.current_request.schema_version == 1 and scene.current_request.phase == "planning", "old v9 free-intent path unchanged")
	scene.switch_playtest(true)
	check(not scene.playtest_mode, "cannot leave pending v9 action")
	scene.cancel_pending(); scene.switch_playtest(true)
	check(scene.playtest.state_copy().state_version == 1 and scene.playtest.authoritative_result().rolls == rolls, "mode roundtrip preserves new independent facts")
	scene.goal.text = "随意新的文字"; scene.submit_action(); scene.playtest_fixture()
	check(scene.playtest.phase() == "awaiting_assessment", "arbitrary UI input cannot receive fixture plan")
	var assessment: Dictionary = Story.assessment(scene.current_request, "fixture_listen", ["certain", "certain"])
	assessment.provenance = {"provider": "human", "kind": "model_reply", "live": false}
	check(scene.apply_decision(assessment) and scene.playtest.phase() == "ready_roll", "free text supports manual offline assessment")
	scene.roll_dice(); scene.roll_dice(); scene.roll_dice()
	check(scene.playtest.state_copy().state_version == 2 and scene.playtest.state_copy().items.item_wine.quantity == 2, "manual listen loop commits its fixed no-cost branch")
	print("AI-GM PLAYTEST MAIN UI: %d checks, %d failures" % [count, failed.size()])
	scene.queue_free()
	await process_frame
	quit(0 if failed.is_empty() else 1)
