extends RefCounted
## Optional public explanation of the EXISTING temporary coast rule/resolvers.
## Does not generate assessments, add mechanics or reveal hidden world data.
static func instructions() -> String:
	return """Only use these contracts when request.contract.calculator is ai_gm_test_coast_actions/v1 and the resolver ID is registered in request.contract.resolver_ids. These are temporary demonstration rules, not final balance.
The legacy coast_move/observe/talk/rest/repair and coast_move_path_v2 contracts each require exactly one component with their action kind (move/observe/talk/rest/repair). Their parameters are exactly integer A and D in 0..4, P in -2..2. Versioned typed families may require two components and additional bounded numeric effect parameters, as explicitly documented in request.contract.action_schemas; never assume one component for all actions. Assess those parameters and disposition from public facts, without inventing fixed thresholds or dice. The temporary calculator uses clamp(5000+1000*(A-D+P),500,9500) for possible actions; certain/impossible are direct outcomes. Facts and intended effects must justify the assessment.
coast_move: bindings exactly {actor_id:'actor_player',target_hex:[q,r]}. Explicit intent must name its destination or otherwise identify it unambiguously; attention alone is not intent. Only an adjacent different legal dry land hex is allowed. At least 1 stamina is required. Success moves there and costs 1 stamina; failure has no patches. The trusted engine also checks detailed terrain clearance unavailable to the model; do not claim access to it.
coast_move_path_v2 (only when registered): bindings exactly {actor_id:'actor_player',target_hex:[q,r]}, component id move. Explicit intent names one destination. The trusted engine finds a deterministic shortest route of adjacent legal dry supports, respecting current blocking and exact physical water-contact checks. Existing active flight may pass ground-only blockers but never bypass dry-support/water clearance. Each traversed edge costs 1 stamina; success requires total cost within current stamina, applies the full frozen route atomically, and advances one turn with hooks/patrol once. Unreachable or unaffordable plans are rejected without partial movement or costs; a assessed failure stays in place with no movement stamina cost. The model never supplies a route or effects.
coast_observe: bindings exactly {actor_id:'actor_player'}. This installed action is narrowly observing the South Tide coast / old lighthouse clues. Success sets only coast_observed=true. It does not discover arbitrary new inventory, secrets or mechanics. Failure changes no facts.
coast_talk: bindings exactly {actor_id:'actor_player',target_actor_id:'actor_keeper'}. This is offering one carried fruit wine to keeper 芦灯 while asking about the extinguished lighthouse and missing ships; do not substitute it for arbitrary dialogue or other targets. Must be within one hex, with at least one wine and one stamina. Both success and failure cost 1 wine and 1 stamina; success also sets keeper_trust=true. Choose 'possible' for uncertain persuasion rather than guaranteeing success.
coast_rest: bindings exactly {actor_id:'actor_player'}. This is resting in place to recover up to 2 missing stamina; full stamina is not a valid restorative action. Success restores min(2,missing_stamina); failure does not change facts.
coast_repair (only when registered): bindings exactly {actor_id:'actor_player'}. This finite chapter action fixes and relights the old lamp beside keeper 芦灯. Requires coast_observed=true, lamp_restored=false, distance to keeper at most one hex, and 2 stamina (1 when keeper_trust=true). Both outcomes spend that stamina; success sets lamp_restored=true. It does not resolve the missing fleet or add arbitrary effects. Already-restored lamps cannot be repaired again.
coast_manipulate_environment_v1 (only when registered): follow its published action_schema exactly. Bind an explicit living actor, actual source-bound nearby standing tree target_entity_id, and operation:'fell'; components control and force both use A/D/P and must both succeed to fell the tree. Cite /actors/<actor_id>, /hexes/<owning_q,r>, and /attention_focus/facts/entity in both components. The source entity must actually appear in frozen public attention; attention is evidence, never permission to act. The program fixes cost at 2 stamina on every outcome and on success makes a sparse fallen object record plus its owning ground block. It does not topple arbitrary mountains/buildings, create objects, or accept arbitrary effect JSON.
coast_apply_condition_v1 (only when registered): bind actor_id, target_actor_id, source_item_id; components delivery (A/D/P) and effect (A/D/P plus integer duration 1..3 and magnitude 1..3). Both checks must succeed for the condition. The authored item's public condition_source fixes kind/caps/target scope; flight magnitude is 1 and targets self only; poison targets self or a living adjacent actor. Both components cite acting actor, target actor and source item facts. The program charges the authored profile units_per_use (1..3) and 1 stamina on all outcomes; no stacking/refresh of the same kind. New conditions first tick on the next committed turn; poison damage floors health at zero. This is not a complete combat, hostility or medicine system. Saves are not granted source items by migration.
A registered status_tick hook may apply bounded poison damage and decrease or expire active conditions once at commit. Loading/replaying an already committed turn never ticks again. Active flight bypasses ground-blocked cells, never air_blocked/all_blocked or unimplemented water crossings. A registered patrol hook may also move the scout during commit; only the authoritative result describes its actual movement. If multiple requested effects cannot be represented by a single contract, ask the player to split the intent via the unsupported error envelope rather than silently dropping parts. The public contract and engine may reject semantically unsupported or numerically invalid answers. Preserve these limits honestly in narration."""
